"""gen_menu_width_table.py - Measure real glyph widths from the ff5c 2bpp menu font.

Replaces the hand-estimated width table in prototype_2bpp_vwf.py with widths
measured from the actual pixel data at $D1F000 (file 0x11F000) in ff5c.sfc.

Method:
  - Decode each of the 256 2bpp tiles (8x8, 16 bytes each)
  - INK = palette colors 2/3 (BP1 set). Color 1 is the baked-in background
    fill (the whole tile is flooded with it), so it must NOT count as ink.
  - Width = rightmost inked column + 2  (glyph width + 1px letter spacing)
  - Clamped to [3, 8]  (menu font tiles are 8px wide, hardware limit)
  - No-ink tiles default to 8 (unknown/icon safety), except $FF (space) = 4
  - $00 is the string terminator (never rendered), width set to 0

Outputs:
  - ffv-decomp/asm/menu_vwf_widths.asm  (asar `db` include, 256 entries)
  - out/vwf_test/vwf_v2_proof.png       (VWF render proof with measured widths)
  - stdout summary of interesting widths

Usage:
    python gen_menu_width_table.py ["Optional proof string"]
"""

import sys
from pathlib import Path

ROOT = Path(r"C:\Users\xj4x\Documents\5work\crawler")
ROM_PATH = ROOT / "ff5c.sfc"
FONT_OFFSET = 0x11F000          # $D1F000 HiROM
OUT_ASM = ROOT / "ffv-decomp" / "asm" / "menu_vwf_widths.asm"
OUT_DIR = ROOT / "out" / "vwf_test"

sys.path.insert(0, str(ROOT / "ffv-decomp" / "analysis-tools"))
from prototype_2bpp_vwf import (
    decode_2bpp_tile, VWFRenderer, build_char_map, tiles_to_image, PALETTE,
)


def measure_widths(rom: bytes) -> list:
    widths = []
    for code in range(256):
        tile = rom[FONT_OFFSET + code * 16 : FONT_OFFSET + code * 16 + 16]
        grid = decode_2bpp_tile(tile)
        rightmost = -1
        for row in grid:
            for x in range(8):
                if row[x] >= 2 and x > rightmost:   # ink = BP1 set (colors 2,3)
                    rightmost = x
        if rightmost < 0:
            widths.append(4 if code == 0xFF else 8)   # blank: space=4, else 8
        else:
            widths.append(max(3, min(8, rightmost + 2)))
    widths[0x00] = 0    # NUL terminator, never rendered
    return widths


def write_asm_table(widths: list):
    lines = [
        "; menu_vwf_widths.asm - GENERATED by gen_menu_width_table.py",
        "; Measured from ff5c.sfc menu font at $D1F000. Do not hand-edit;",
        "; regenerate after font changes. Indexed by RAW char code (0-255).",
        "",
        "MenuVWF_WidthTable:",
    ]
    for row in range(16):
        chunk = widths[row * 16 : row * 16 + 16]
        vals = ",".join(f"${v:02X}" for v in chunk)
        lines.append(f"    db {vals}    ; ${row * 16:02X}-${row * 16 + 15:02X}")
    lines.append("")
    OUT_ASM.write_text("\n".join(lines), encoding="ascii")
    print(f"Wrote {OUT_ASM}")


def main():
    proof_text = sys.argv[1] if len(sys.argv) > 1 else "Will o' Wisp 999"
    rom = ROM_PATH.read_bytes()
    widths = measure_widths(rom)
    write_asm_table(widths)

    char_map = build_char_map()
    print("\nSample measured widths (menu font, ff5c):")
    for ch in "iIlMWmw.!0958 ABZ":
        code = 0xFF if ch == " " else char_map.get(ch)
        if code is not None:
            print(f"  '{ch}' (${code:02X}) = {widths[code]}px")

    # Proof render using the measured table, modeling the ASM's bg handling:
    # strip color-1 background at load (BP0 &= BP1), OR-merge sparse ink,
    # then finalize (BP0 |= ~BP1) to repaint the opaque background.
    class BgAwareRenderer(VWFRenderer):
        def load_tile(self, char_code):
            super().load_tile(char_code)
            for row in range(8):
                self.tile_buf[row * 2] &= self.tile_buf[row * 2 + 1]

        def finalize(self):
            for col in range(32):
                for row in range(8):
                    i = col * 16 + row * 2
                    self.dest_buffer[i] |= self.dest_buffer[i + 1] ^ 0xFF

    r = BgAwareRenderer(rom, FONT_OFFSET)
    r.set_width_table(widths)
    r.reset()
    for ch in proof_text:
        code = 0xFF if ch == " " else char_map.get(ch)
        if code is not None:
            r.render_char(code)
    r.finalize()
    vwf_px = r.get_rendered_width()
    fixed_px = 8 * len(proof_text)
    print(f"\nProof: '{proof_text}' -> VWF {vwf_px}px vs fixed {fixed_px}px "
          f"({100 * (fixed_px - vwf_px) // fixed_px}% saved)")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    img = tiles_to_image(r.get_rendered_tiles(), palette=PALETTE)
    if img:
        img.save(OUT_DIR / "vwf_v2_proof.png")
        print(f"Proof image: {OUT_DIR / 'vwf_v2_proof.png'}")


if __name__ == "__main__":
    main()
